[package]
name = "ebits"
version = "0.1.0"
authors = ["Seth Stadick <seth_stadick@bio-rad.com>"]
edition = "2018"

[dependencies]
croaring = "0.4"

[dev-dependencies]
criterion = "0.3"
rand = "0.7"

[[bench]]
name = "ebits_benchmarks"
harness = false
